/**
 * SVG → React component pipeline.
 *
 * Reads all `category--name.svg` files from src/icons/svg/, runs SVGR on each,
 * writes components to src/icons/components/, and generates the barrel + manifest.
 *
 * Usage: npm run icons:generate
 */

import { transform } from "@svgr/core";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SVG_DIR = path.resolve(__dirname, "../src/icons/svg");
const OUT_DIR = path.resolve(__dirname, "../src/icons/components");
const MANIFEST_PATH = path.resolve(__dirname, "../src/icons/manifest.ts");

/** Converts `category--name` filename stem to a valid PascalCase identifier. */
function toPascalCase(stem: string): string {
  return stem
    .replace(/--/, "-")
    .split(/[-\s]+/)                          // split on hyphens and spaces
    .filter(Boolean)
    .map((part) => {
      const clean = part.replace(/[^a-zA-Z0-9]/g, ""); // strip !, ?, . etc.
      return clean ? clean.charAt(0).toUpperCase() + clean.slice(1) : "";
    })
    .filter(Boolean)
    .join("");
}

/** Represents a single icon entry in the manifest. */
export interface IconManifestEntry {
  /** Icon name without category prefix (e.g. "chevron-right"). */
  name: string;
  /** Icon category (e.g. "navigation"). */
  category: string;
  /** PascalCase React component name (e.g. "NavigationChevronRight"). */
  componentName: string;
}

async function main(): Promise<void> {
  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

  const svgFiles = fs
    .readdirSync(SVG_DIR)
    .filter((f) => f.endsWith(".svg"))
    .sort();

  const manifest: IconManifestEntry[] = [];
  const barrelLines: string[] = [];

  for (const file of svgFiles) {
    const stem = file.replace(/\.svg$/, ""); // e.g. "navigation--chevron-right"
    const [category, ...nameParts] = stem.split("--");
    const name = nameParts.join("--"); // everything after the first "--"
    const componentName = toPascalCase(stem);
    const outFile = path.join(OUT_DIR, `${componentName}.tsx`);

    const svgContent = fs.readFileSync(path.join(SVG_DIR, file), "utf-8");

    const code = await transform(
      svgContent,
      {
        typescript: true,
        jsxRuntime: "automatic",
        svgProps: { "aria-hidden": "true" },
        plugins: ["@svgr/plugin-svgo", "@svgr/plugin-jsx"],
        svgoConfig: {
          plugins: [
            {
              name: "preset-default",
              params: {
                overrides: {
                  removeViewBox: false,
                  // Convert all hex colors to currentColor so icons inherit color from CSS
                  convertColors: { currentColor: /^#/ },
                },
              },
            },
            "removeDimensions",
          ],
        },
      },
      { componentName }
    );

    fs.writeFileSync(outFile, code, "utf-8");
    barrelLines.push(`export { default as ${componentName} } from "./${componentName}";`);
    manifest.push({ name, category: category ?? "misc", componentName });

    console.log(`  ✓  ${componentName}`);
  }

  // Barrel index
  fs.writeFileSync(
    path.join(OUT_DIR, "index.ts"),
    barrelLines.join("\n") + "\n",
    "utf-8"
  );

  // Manifest
  const manifestContent = `// Auto-generated by scripts/generate-icons.ts — do not edit manually.
import type { IconManifestEntry } from "./manifest";

export type { IconManifestEntry };

export const iconManifest: IconManifestEntry[] = ${JSON.stringify(manifest, null, 2)};

export const iconNames = iconManifest.map((e) => e.name);
`;
  fs.writeFileSync(MANIFEST_PATH, manifestContent, "utf-8");

  console.log(`\nGenerated ${svgFiles.length} icon(s).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
